### ISSUE TITLE
Alarm Causes - 

### ISSUE THREAD

**Issue by cybertza** [MnrGreg/homebridge-paradox-security-system#8]
I made this node red path at the bottom , that basically (in the easiest way i know) strips off the extra data from the alarm:
Taking this:
Event:Zone in alarm;SubEvent:PATIO BEAM
To:
Event:Zone in alarm;

Due to the fact that the Parser does not do Regxp and is rather specific.
When i trigger the alarm, I receive via The HOME APP But then the app start flaring up with the Alarm Icon and No Response

Here is the Node Red Hack:
Te elegant way would be to parse the data better from the MQTT, but the work around works  
[{"id":"49634e22.e5dad","type":"mqtt in","z":"241a68de.5be0f8","name":"Paradox/Events","topic":"Paradox/Events","qos":"2","broker":"d2514633.e1de68","x":157.96874237060547,"y":2551.5907821655273,"wires":[["71f94bef.3ffd34"]]},{"id":"bed05b4d.6dbe98","type":"mqtt out","z":"241a68de.5be0f8","name":"","topic":"Paradox/Events","qos":"","retain":"","broker":"d2514633.e1de68","x":767.9686813354492,"y":2550.6813735961914,"wires":[]},{"id":"71f94bef.3ffd34","type":"switch","z":"241a68de.5be0f8","name":"find alarm","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"Event:Zone in alarm","vt":"str"},{"t":"cont","v":"Event:Zone in alarm;SubEvent:PATIO BEAM","vt":"str"}],"checkall":"true","outputs":2,"x":345.80255126953125,"y":2551.2074222564697,"wires":[[],["bb6543b5.5d50e"]]},{"id":"bb6543b5.5d50e","type":"change","z":"241a68de.5be0f8","name":"Event:Zone in alarm;","rules":[{"t":"set","p":"payload","pt":"msg","to":"Event:Zone in alarm","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":550.6960067749023,"y":2554.318386077881,"wires":[["bed05b4d.6dbe98"]]},{"id":"d2514633.e1de68","type":"mqtt-broker","z":"","broker":"172.16.103.9","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"willTopic":"","willQos":"0","willPayload":"","birthTopic":"","birthQos":"0","birthPayload":""}]

**Comment by MnrGreg** [comment]
Hi @cybertza 

Check out the work @e-mcgee has done to consolidate the code from IP150-MQTTv2 directly into node.js. This is the right approach in my view and is working well.

https://github.com/e-mcgee/paradox_platform
